name:
  build
on:
  push
jobs:
  build:
    if: |
      !contains(github.event.head_commit.message, 'SKIP')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: alaviss/setup-nim@master
        with:
          path: '../nim'
          version: 'version-1-4'
      - run: "nimble -y test && nimble install -y"
      - run: "hmisc-putils docgen"
      - uses: crazy-max/ghaction-github-pages@v1
        with:
          build_dir: docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
